version: "3.9"

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: app
    links:
      - postgres
    depends_on:
      - postgres
    command:
      - --connection-string=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB
      - --port=8080
  nginx:
    build: nginx
    ports:
      - "8080:80"
    environment:
      UPSTREAM_APP: app:8080
    links:
      - app
    depends_on:
      - app

volumes:
  pgdata:
